### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by byronwwang** [viorik/unsupgpu#6]
During the installation, I got the following error.

-- Found Torch7 in /home/wangwei/utils/torch/install
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:1428 (add_library):
  add_library cannot create target "unsupgpu" because another target with the
  same name already exists.  The existing target is a module library created
  in source directory "/tmp/luarocks_unsupgpu-0.1-0-800/unsupgpu".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /home/wangwei/utils/torch/install/share/cmake/torch/TorchPackage.cmake:12 (CUDA_ADD_LIBRARY)
  CMakeLists.txt:22 (ADD_TORCH_PACKAGE)

**Comment by viorik** [comment]
Hi @byronwwang,
I think your issue looks similar to [this one](https://github.com/viorik/extracunn/issues/1). Do you have a red hat server or what is your configuration? Anyway, please check the solution suggested there and let me know if it works or not.
cheers.

**Comment by byronwwang** [comment]
## @viorik Yes, I use CentOS 7.0. Unfortunately, I got a new error.

CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:1428 (add_library):
  add_library cannot create target "unsupgpu" because another target with the
  same name already exists.  The existing target is a module library created
  in source directory "/tmp/luarocks_unsupgpu-0.1-0-1951/unsupgpu".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /home/wangwei/utils/torch/install/share/cmake/torch/TorchPackage.cmake:12 (CUDA_ADD_LIBRARY)
  CMakeLists.txt:22 (ADD_TORCH_PACKAGE)

**Comment by viorik** [comment]
Is this a new error? Looks identical to the previous one. The solution suggested in the other issue didn't work?

**Comment by byronwwang** [comment]
@viorik Opps! That's really the same error. I think I have pasted the provided codes in wrong place. Could you give me some instruction? Where should I past them? Do  I need to comment out 'ADD_TORCH_PACKAGE'?

**Comment by viorik** [comment]
Unfortunately I cannot test this myself, since I don't have that configuration. From the suggested solution, it seems that you need to modify the CMakeLists.txt file, and copy the given code to replace everything that comes from line 21 onwards.
