### ISSUE TITLE
require 'unsupgpu' failed

### ISSUE THREAD

**Issue by gxyEPFL** [viorik/unsupgpu#7]
I try to run the demo lua file. I follow the installation construction also. Before `luarocks install unsupgpu-0.1-0.rockspec` I also use`cmake`and`make install`to install.  But the `require 'unsupgpu'`failed. Anybody has any clue? 
`lua: demo.lua:8: module 'unsupgpu' not found:
        no field package.preload['unsupgpu']
`

**Comment by viorik** [comment]
Did you try just `luarocks make`  inside the folder?

**Comment by gxyEPFL** [comment]
thanks for your quick reply. Sorry, I should use `luarocks make` and it works now
